from flask import Flask, jsonify, request, send_from_directory

from genetic_drift import plot_genetic_drift
    
app = Flask(__name__)

@app.route('/process_data', methods=['POST'])
def process_data():
    """
    Process the data received from the frontend and generate a plot HTML based on the slider values.

    Parameters:
        None

    Returns:
        A JSON object containing the plot HTML.

    """
    data = request.get_json()

    # Retrieve slider values from the frontend
    p0 = float(data['p0'])
    Ne = int(data['Ne'])
    nrep = int(data['nrep'])
    time = int(data['time'])
    show = data['show']
    time_filter_start = int(data['time_filter_start']) 
    time_filter_end = int(data['time_filter_end'])
    rep_filter = int(data['rep_filter'])

    # Generate the plot HTML based on the slider values
    plot_html = plot_genetic_drift(p0, Ne, nrep, time, show, [time_filter_start, time_filter_end], rep_filter)
    
    return jsonify(plot_html=plot_html)

@app.route('/')
def index():
    """
    A function that serves as the route handler for the root URL ("/").
    
    Returns:
        The response generated by the `send_from_directory` function, which is responsible for sending the 'index.html' file from the 'static' directory.
    """
    return send_from_directory('static', 'index.html')

if __name__ == '__main__':
    app.run(port=8080)
